{
 "title": "Kandula App Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests Per Minute",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kandula_app_monitor_views_sec_count{job=\"kandula-app-service\"}[1m]))",
     "legendFormat": "kandula-app-service"
    }
   ]
  },
  {
   "title": "Requests Per Second (1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kandula_app_monitor_views_sec_count{method=\"view_home\"}[1m]) * 100",
     "legendFormat": "Home"
    },
    {
     "expr": "rate(kandula_app_monitor_views_sec_count{method=\"view_scheduler\"}[1m]) * 100",
     "legendFormat": "Scheduler"
    },
    {
     "expr": "rate(kandula_app_monitor_views_sec_count{method=\"view_metrics\"}[1m]) * 100",
     "legendFormat": "Metrics"
    },
    {
     "expr": "rate(kandula_app_monitor_views_sec_count{method=\"view_about\"}[1m]) * 100",
     "legendFormat": "About"
    },
    {
     "expr": "rate(kandula_app_monitor_views_sec_count{method=\"view_health\"}[1m]) * 100",
     "legendFormat": "Health"
    },
    {
     "expr": "rate(kandula_app_monitor_views_sec_count{method=\"view_instances\"}[1m])",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Views Per Page",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_home\"}",
     "legendFormat": "Home"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_scheduler\"}",
     "legendFormat": "Scheduler"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_metrics\"}",
     "legendFormat": "Metrics"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_about\"}",
     "legendFormat": "About"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_health\"}",
     "legendFormat": "Health"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_instances\"}",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Avg. Response Time (1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(kandula_app_monitor_views_sec_sum{method=\"view_home\"}[1m])",
     "legendFormat": "Home"
    },
    {
     "expr": "increase(kandula_app_monitor_views_sec_sum{method=\"view_scheduler\"}[1m])",
     "legendFormat": "Scheduler"
    },
    {
     "expr": "increase(kandula_app_monitor_views_sec_sum{method=\"view_metrics\"}[1m])",
     "legendFormat": "Metrics"
    },
    {
     "expr": "increase(kandula_app_monitor_views_sec_sum{method=\"view_about\"}[1m])",
     "legendFormat": "About"
    },
    {
     "expr": "increase(kandula_app_monitor_views_sec_sum{method=\"view_health\"}[1m])",
     "legendFormat": "Health"
    },
    {
     "expr": "increase(kandula_app_monitor_views_sec_sum{method=\"view_instances\"}[1m])",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Page Views Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_home\"}",
     "legendFormat": "Home"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_scheduler\"}",
     "legendFormat": "Sheduler"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_metrics\"}",
     "legendFormat": "Metrics"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_about\"}",
     "legendFormat": "About"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_health\"}",
     "legendFormat": "Health"
    },
    {
     "expr": "kandula_app_monitor_views_sec_count{method=\"view_instances\"}",
     "legendFormat": "Instances"
    }
   ]
  }
 ]
}