---
- name: Download Filebeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.11.0-amd64.deb
    dest: /home/ubuntu/filebeat-oss-7.11.0-amd64.deb

- name: Install Filebeat
  apt:
    deb: /home/ubuntu/filebeat-oss-7.11.0-amd64.deb

- name: Copy Filebeat config file
  copy:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Copy Filebeat health check file
  copy:
    src: filebeat_health_check.sh
    dest: /home/ubuntu/filebeat_health_check.sh
    mode: a+x

- name: Start Filebeat
  ansible.builtin.service:
    name: filebeat
    state: started

- name: Copy Filebeat K8s config file
  copy:
    src: filebeat-k8s-config.yaml
    dest: /home/ubuntu/filebeat-k8s-config.yaml
  when: service == "ansible"

- name: Copy Filebeat K8
  replace:
    path: /home/ubuntu/filebeat-k8s-config.yaml
    regexp: "<you elk host private ip>"
    replace: "{{ elk_private_ip }}"
  when: service == "ansible"

- name: Deploy filebeat on K8s
  shell: "kubectl apply -f filebeat-k8s-config.yaml"
