---
- name: Download Elasticsearch
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.10.2-amd64.deb
    dest: /home/ubuntu/elasticsearch-oss-7.10.2-amd64.deb
    owner: ubuntu
    group: ubuntu

- name: Download Kibana
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-oss-7.10.2-amd64.deb
    dest: /home/ubuntu/kibana-oss-7.10.2-amd64.deb
    owner: ubuntu
    group: ubuntu

- name: Install Elasticsearch
  apt:
    deb: /home/ubuntu/elasticsearch-oss-7.10.2-amd64.deb

- name: Install Kibana
  apt:
    deb: /home/ubuntu/kibana-oss-7.10.2-amd64.deb

- name: Copy Elasticsearch config file
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml

- name: Configure Server hosts
  shell: |
    echo 'server.host: "0.0.0.0"' > /etc/kibana/kibana.yml

- name: Start Elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    state: restarted

- name: Start Kibana
  ansible.builtin.service:
    name: kibana
    state: restarted

- name: Copy Kandula Objects file
  copy:
    src: kandula-objects.ndjson
    dest: /home/ubuntu/kandula-objects.ndjson
    owner: ubuntu
    group: ubuntu

- name: Create Kandula Objects In Kibana
  shell: 'curl -X POST elk.kandula:5601/api/saved_objects/_import -H "kbn-xsrf: true" --form file=@/home/ubuntu/kandula-objects.ndjson'
  # shell: 'curl -X POST elk.kandula:5601/api/saved_objects/_import?createNewCopies=true -H "kbn-xsrf: true" --form file=@/home/ubuntu/kandula-objects.ndjson'
  ignore_errors: true
