---
# defaults file for install-consul
consul_dc_name: "consul_dc"
k8s_consul_svc_ip: "172.16.0.10"
consul_servers_count: 3
consul_gossip_encryption_key: "uDBV4e+LbFW3019YKPxIrg=="
dnsmasq_config_path: /etc/dnsmasq.d/10-consul
resolved_config_path: /etc/systemd/resolved.conf
consul_url: https://releases.hashicorp.com/consul/1.11.1/consul_1.11.1_linux_amd64.zip
