---
- name: Install Java
  apt:
    name:
      - openjdk-11-jdk
    update_cache: yes
    state: present

- name: Create Jenkins Node Home Folder
  file:
    path: /home/ubuntu/jenkins_home
    state: directory
    group: "ubuntu"
    mode: "0777"
