---
- name: Install Java
  apt:
    name:
      - openjdk-11-jdk
      - python3-venv
      - libpq-dev
      - python-psycopg2
    update_cache: yes
    state: present

- name: pip3 Update
  command: "pip3 install --upgrade pip"
