---
- name: Create Jenkins Folders
  file:
    path: /home/ubuntu/jenkins_home
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Start Jenkins Container
  community.docker.docker_container:
    name: jenkins
    image: jenkins/jenkins
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
      - "50000:50000"
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - /home/ubuntu/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: yes

- name: Install Jenkins Plugins
  shell: docker exec jenkins /bin/bash -c '/usr/local/bin/install-plugins.sh {{ item }}'
  with_items:
    [
      "build-pipeline-plugin",
      "ssh-slaves",
      "github-branch-source",
      "blueocean",
      "slack",
      "build-monitor-plugin",
      "docker-workflow",
      "kubernetes-cd",
    ]
  changed_when: true

- name: Copy Kandula Job folder
  copy:
    src: files/kandula-cicd
    dest: /home/ubuntu/jenkins_home/jobs/
    force: no
    owner: ubuntu
    group: ubuntu

- name: Restart Jenkins Container
  shell: docker restart jenkins
